exclude_patterns:
- 'app/assets/'
- 'app/helpers/'
- 'app/jobs/'
- 'app/mailers/'
- 'app/channels/*'
- 'app/controllers/application_controller.rb'
- 'app/errors/'
- 'app/views/'
- 'config/'
- 'db/'
- 'lib/'
- 'log/'
- 'public/'
- 'spec/'
- 'tmp/'
- 'vendor/'
- 'config/'
- 'bin/'
- 'coverage/'