language: ruby
rvm:
  - 2.3.3

addons:
  code_climate:
    repo_token: df0062342f50a2fcb9b7c63b726b4058e4b17b7d5f0b35d1994d482a18a25303

env:
  global:
    - RAILS_ENV=test
    - CC_TEST_REPORTER_ID=df0062342f50a2fcb9b7c63b726b4058e4b17b7d5f0b35d1994d482a18a25303

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER \"gps\" WITH PASSWORD 'gps';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"gps_test\";" -U postgres
  - psql -c "CREATE DATABASE \"gps_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - gem install bundler
  - bundle install --retry=3

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  bundler: true
